<template>
  <div
    relative
    rounded-10
    bg-gradient-to-b
    from-white
    from-opacity-3
    to-white
    to-opacity-5
    h-full
    p-4
    before:mask
    before:content-empty
    before:rounded-10
    before:absolute
    before:inset-none
    before:pointer-events-none
    before:select-none
    before:p-px
  >
    <slot />
  </div>
</template>
